rogues_den/auth.py
from flask import (Blueprint, render_template,
                   request, flash, redirect, url_for, session)
from .models import Users
from werkzeug.security import generate_password_hash, check_password_hash
from rogues_den import db
from flask_login import login_user, logout_user, login_required, current_user

auth = Blueprint('auth', __name__)


@auth.route("/login", methods=["GET", "POST"])
def login():
    if request.method == "POST":
        email = request.form.get("email")
        password = request.form.get("password")

        user = Users.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash("Welcome back, {}!".format(user.fname),
                      category="success")
                login_user(user, remember=True)
                return redirect(url_for("characters"))
            else:
                flash("Email or Password incorrect", category="danger")

            return render_template("login.html", email=email)

        return render_template("login.html", user=current_user)

    return render_template("login.html")


@auth.route("/register", methods=["GET", "POST"])
def register():
    if request.method == "POST":
        username = request.form.get("username")
        email = request.form.get("email")
        fname = request.form.get("fname")
        lname = request.form.get("lname")
        password1 = request.form.get("password1")
        password2 = request.form.get("password2")

        # Perform validation checks
        user = Users.query.filter_by(email=email).first()
        if user:
            flash("Username already exists.", category="danger")
        elif user:
            flash("Email already registered.", category="danger")
        elif len(email) < 11:
            flash("Email must be at least 11 characters long.",
                  category="danger")
        elif len(fname) < 2:
            flash("First name is too short.", category="danger")
        elif len(lname) < 2:
            flash("Last name is too short.", category="danger")
        elif password1 != password2:
            flash("Passwords don't match.", category="danger")
        elif len(password1) < 7:
            flash("Password too short, must be at least 7 characters.",
                  category="danger")
        else:
            # Create and add the new user to the database
            new_user = Users(username=username, email=email, fname=fname,
                             lname=lname, password=generate_password_hash
                             (password1, method="pbkdf2:sha256"))
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            flash("New Account Created!", category="success")
            return redirect(url_for("characters"))

        # If validation fails, pass the form data back to the template
        return render_template("register.html", username=username,
                               email=email, fname=fname, lname=lname)

    # Render the registration page for a GET request
    return render_template("register.html")


@auth.route("/logout")
def logout():
    logout_user()
    flash("You've been successfully logged out", category="success")
    return redirect(url_for("home"))

rogues_den/templates/add_character.html
{% extends "base.html" %}
{% block content %}
    <div class="container">
        <h3 class="center-align white-text shadow">Create Your Character</h3>
    </div>

    <div class="container">
        <form method="POST" action="{{ url_for('add_character') }}">

            <!-- Character Name -->
            <div class="input-field center-align white-text shadow">
                <label for="character_name" class="white-text">Character Name</label>
                <input type="text" id="character_name" name="character_name" class="white-text" data-length="20" maxlength="15" required>
            </div>

            <!-- Character Race and Class -->
            <div class="row">
                <div class="input-field col s6 m6 l6">
                    <select name="character_race" class="browser-default white-text shadow" required aria-label="Select a Race">
                        <option value="" disabled selected>Select a Race</option>
                        {% for race in races %}
                        <option value="{{ race }}">{{ race }}</option>
                        {% endfor %}
                    </select>
                </div>

                <div class="input-field col s6 m6 l6">
                    <select name="character_class" class="browser-default white-text shadow" required aria-label="Select a Class">
                        <option value="" disabled selected>Select a Class</option>
                        {% for chcls in classes %}
                        <option value="{{ chcls }}">{{ chcls }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>

            <!-- Character level -->
            <div class="input-field white-text shadow">
                <label for="character_level" class="white-text">Level</label>
                <input type="number" id="character_level" name="character_level" min="1" max="20" class="white-text" required>
            </div>

            <!-- Character stats -->
            <div class="row">

                <div class="input-field col s4 m4 l4 white-text shadow">
                    <label for="character_strength" class="white-text" id="strlab"></label>
                    <input type="number" id="character_strength" name="character_strength" min="1" max="20" class="white-text" required>
                </div>

                <div class="input-field col s4 m4 l4 white-text shadow">
                    <label for="character_dexterity" class="white-text" id="dexlab"></label>
                    <input type="number" id="character_dexterity" name="character_dexterity" min="1" max="20" class="white-text" required>
                </div>
            

                <div class="input-field col s4 m4 l4 white-text shadow">
                    <label for="character_constitution" class="white-text" id="conlab"></label>
                    <input type="number" id="character_constitution" name="character_constitution" min="1" max="20" class="white-text" required>
                </div>

                <div class="input-field col s4 m4 l4 white-text shadow">
                    <label for="character_intelligence" class="white-text" id="intlab">e</label>
                    <input type="number" id="character_intelligence" name="character_intelligence" min="1" max="20" class="white-text" required>
                </div>

                <div class="input-field col s4 m4 l4 white-text shadow">
                    <label for="character_wisdom" class="white-text" id="wislab"></label>
                    <input type="number" id="character_wisdom" name="character_wisdom" min="1" max="20" class="white-text" required>
                </div>

                <div class="input-field col s4 m4 l4 white-text shadow">
                    <label for="character_charisma" class="white-text" id="chalab"></label>
                    <input type="number" id="character_charisma" name="character_charisma" min="1" max="20" class="white-text" required>
                </div>
            </div>

            <!-- Character background -->
            <div class="input-field white-text shadow">
                <label for="character_background" class="white-text">Background</label>
                <textarea id="character_background" name="character_background" class="materialize-textarea white-text"></textarea>
            </div>
            
            <!-- Add character -->
            <div class="center-align">
                <button class="btn-large shadow" type="submit" aria-label="Add character button"><i class="material-icons">Add Character</i></button>
            </div>
        </form>
    </div>
{% endblock %}

rogues_den/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>

    <!-- Meta tags -->
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" 
        content="Rogues Den is a character storage facility for your Dungeons & Dragons campaigns. 
        You can create your character, and as you progress through your campaigns, you can edit them too so they're up to date!">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" 
        integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" 
        crossorigin="anonymous" referrerpolicy="no-referrer">

    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Cinzel:wght@400..900&display=swap" rel="stylesheet">

    <!-- Favicon -->
    <link rel="apple-touch-icon" sizes="180x180" href="{{ url_for('static', filename='favicon/apple-touch-icon.png') }}">
    <link rel="icon" type="image/png" sizes="32x32" href="{{ url_for('static', filename='favicon/favicon-32x32.png') }}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{ url_for('static', filename='favicon/favicon-16x16.png') }}">
    <link rel="manifest" href="{{ url_for('static', filename='favicon/site.webmanifest') }}">
    
    <!-- CSS -->
    <!-- Materialize CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css" type="text/css">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}" type="text/css">

    <!-- Page Title -->
    <title>Rogues Den</title>
</head>
<body>
    
    <header>
        <!-- Top Navbar -->
        <nav class="shadow">
            <div class="nav-wrapper">
                <a href="{{ url_for('home') }}" class="brand-logo center" aria-label="Home page link and site title">Rogues Den</a>
                <a href="#" data-target="mobile-demo" class="sidenav-trigger right" aria-label="Menu"><i class="fa-solid fa-bars"></i></a>
                <ul class="right hide-on-med-and-down">
                    {% if current_user.is_authenticated %}
                    <li><a href="{{ url_for('characters') }}" aria-label="Character page link">Characters</a></li>
                    <li><a href="{{ url_for('profile') }}" aria-label="Profile page link">Profile</a></li>
                    {% else %}
                    <li><a href="{{ url_for('home') }}" aria-label="Home page link">Home</a></li>
                    <li><a href="{{ url_for('auth.login') }}" aria-label="Login page link">Login</a></li>
                    <li><a href="{{ url_for('auth.register') }}" aria-label="Register page link">Register</a></li>
                    {% endif %}
                </ul>
            </div>
        </nav>

        <!-- Mobile SideNav-->
        <ul class="sidenav shadow" id="mobile-demo">
            {% if current_user.is_authenticated %}
            <li><a class="snav white-text" href="{{ url_for('characters') }}" aria-label="Character page link">Characters</a></li>
            <li><a class="snav white-text" href="{{ url_for('profile') }}" aria-label="Profile page link">Profile</a></li>
            {% else %}
            <li><a class="snav white-text" href="{{ url_for('home') }}" aria-label="Home page link">Home</a></li>
            <li><a class="snav white-text" href="{{ url_for('auth.login') }}" aria-label="Login page link">Login</a></li>
            <li><a class="snav white-text" href="{{ url_for('auth.register') }}" aria-label="Register page link">Register</a></li>
            {% endif %}
        </ul>
    </header>

    <!-- Flash messages -->
    {% with messages = get_flashed_messages(with_categories=True) %}
        {% if messages %}
            <div class="container card-panel-message">
                {% for category, message in messages %}
                    <div class="flow-text center-align {{ 'green lighten-4 green-text' if category == 'success' else 'red lighten-4 red-text' }}">
                        {{ message }}
                    </div>
                {% endfor %}
            </div>
        {% endif %}
    {% endwith %}
    
    <!-- Main content including home page content -->
    <main class="container">
        {% block content %}
        <div class="container">
            <div class="row">
                <h2 class="white-text center-align shadow">Welcome, to the Rogues Den!</h2>
            </div>
            <p class="flow-text white-text center-align shadow">
                Here at the Rogues Den you'll be able to keep a record of all of the Dungeons and Dragons characters you've created!
                <br>
                <br>
                Simply log in, or register if you haven't already, and head over to the Character page to start your creation!
                <br>
                <br>
                This site is a work in progress, so please be sure to check back for future updates. 
                <br>
                <br>
                From all of us here at Rogues Den HQ, thank you for your support, and we look forward to providing you with the greatest character storage facility possible! 
                <br>
                <br>
                Good luck on your campaigns, and have fun!
            </p>
        </div>
        {% endblock %}
    </main>

    <!-- Footer -->
    <footer class="page-footer shadow">
            <div class="container">
                © 2024 Rogues Den
                <a class="foottext grey-text text-lighten-4 right" href="https://github.com/CamRaff/Milestone3-RoguesDen" aria-label="GitHub link" target="_blank">&copy; Rogues Den <i class="fa-brands fa-github"></i></a>
            </div>
    </footer>
          
    <!-- Materialize JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <!-- Custom JS -->
    <script src="{{ url_for('static', filename='js/script.js') }}"></script>

</body>
</html>

rogues_den/templates/character_view.html
{% extends "base.html" %}
{% block content %}
    <div class="container">
        <br>
    </div>
    <div class="container">
        <div class="row">
            <!-- Character image -->
            <div class="col s8 offset-s2 m6 offset-m3 l4 offset-l4">
                <!-- Elif to display the correct image for the chosen race -->
                {% if character.character_race == 'Dragonborn' %}
                <img src="{{ url_for('static', filename='images/races/canva-dragonborn.webp') }}" alt="Dragonborn image" class="circle responsive-img">
                {% elif character.character_race == 'Dwarf' %}
                <img src="{{ url_for('static', filename='images/races/canva-dwarf.webp') }}" alt="Dwarf image" class="circle responsive-img">
                {% elif character.character_race == 'Elf' %}
                <img src="{{ url_for('static', filename='images/races/canva-elf.webp') }}" alt="Elf image" class="circle responsive-img">
                {% elif character.character_race == 'Gnome' %}
                <img src="{{ url_for('static', filename='images/races/canva-gnome.webp') }}" alt="Gnome image" class="circle responsive-img">
                {% elif character.character_race == 'Half-Elf' %}
                <img src="{{ url_for('static', filename='images/races/canva-half-elf.webp') }}" alt="Half-Elf image" class="circle responsive-img">
                {% elif character.character_race == 'Halfling' %}
                <img src="{{ url_for('static', filename='images/races/canva-halfling.webp') }}" alt="Halfling image" class="circle responsive-img">
                {% elif character.character_race == 'Half-Orc' %}
                <img src="{{ url_for('static', filename='images/races/canva-half-orc.webp') }}" alt="Half-Orc image" class="circle responsive-img">
                {% elif character.character_race == 'Human' %}
                <img src="{{ url_for('static', filename='images/races/canva-human.webp') }}" alt="Human image" class="circle responsive-img">
                {% elif character.character_race == 'Tiefling' %}
                <img src="{{ url_for('static', filename='images/races/canva-tiefling.webp') }}" alt="Tiefling image" class="circle responsive-img">
                {% endif %}
            </div>

            <!-- Character information -->
            <div class="col s8 offset-s2 center-align m6 offset-m3 l8 offset-l2">
                <p class="flow-text white-text shadow">{{ character.character_name }}</p>
                <p class="flow-text white-text shadow">Level {{ character.character_level }} {{ character.character_race }} {{ character.character_class }}</p>
            </div>
            <div class="col s4 m4 l4">
                <p class="center-align white-text shadow" id="strength" data-strength="{{ character.character_strength }}"></p>
            </div>

            <div class="col s4 m4 l4">
                <p class="center-align white-text shadow" id="dexterity" data-dexterity="{{ character.character_dexterity }}"></p>
            </div>
        
            <div class="col s4 m4 l4">
                <p class="center-align white-text shadow" id="constitution" data-constitution="{{ character.character_constitution }}"></p>
            </div>

            <div class="col s4 m4 l4">
                <p class="center-align white-text shadow" id="intelligence" data-intelligence="{{ character.character_intelligence }}"></p>
            </div>

            <div class="col s4 m4 l4">
                <p class="center-align white-text shadow" id="wisdom" data-wisdom="{{ character.character_wisdom }}"></p>
            </div>

            <div class="col s4 m4 l4">
                <p class="center-align white-text shadow" id="charisma" data-charisma="{{ character.character_charisma }}"></p>
            </div>
        </div>

        <div class="container">
            <!-- Character background -->
                <div class="charbg white-text shadow">
                    <h6 class="center-align white-text">Background</h6>
                    <p class="center-align white-text">{{ character.character_background }}</p>
                </div>

            <!-- Back to characters page or delete -->
            <div class="center-align">
                <a class="waves-effect waves-heavy btn-large shadow" href="{{ url_for('characters') }}" aria-label="Back to character page">Back</a>
                <a class="waves-effect waves-heavy btn-large shadow" href="{{ url_for('edit_character', character_id=character.id) }}" aria-label="Edit character">Edit</a>
                <a class="waves-effect waves-heavy btn-large modal-trigger shadow" href="#modal1" aria-label="Delete character">Delete</a>
            </div>

            <!-- Modal -->
            <div id="modal1" class="modal shadow">
                <div class="modal-content center-align white-text shadow">
                  <h4>Are you sure you want to delete {{ character.character_name }}?</h4>
                  <p>Once you press 'Delete', your character will be gone forever. Are you sure that is what you want to do?</p>
                </div>
                <div class="center-align shadow">
                  <a href="#!" class="modal-close waves-effect waves-green btn white-text shadow" aria-label="Cancel and back to view">Cancel</a>
                  <a href="{{ url_for('delete_character', character_id=character.id) }}" class="modal-close waves-effect waves-green btn white-text shadow" aria-label="Confirm and delete">Yes, delete {{ character.character_name }}</a>
                </div>
            </div>
        </div>
    </div>
    <!-- script for changing inner html of stats on smaller screens -->
    <script>
        // strength
        // const character_strength = "{{ character.character_strength }}"
        // function updateStrength() {
        //     const strengthElement = document.getElementById("strength");

        //     if (window.innerWidth > 500) {
        //         strengthElement.innerHTML = "Strength: " + character_strength;
        //     } else {
        //         strengthElement.innerHTML = "Str: " + character_strength;
        //     }
        // }

        // dexterity
        // const character_dexterity = "{{ character.character_dexterity }}"
        // function updateDexterity() {
        //     const strengthElement = document.getElementById("dexterity");

        //     if (window.innerWidth > 500) {
        //         strengthElement.innerHTML = "Dexterity: " + character_dexterity;
        //     } else {
        //         strengthElement.innerHTML = "Dex: " + character_dexterity;
        //     }
        // }
        
    </script>
{% endblock %}

rogues_den/templates/characters.html
{% extends "base.html" %}
{% block content %}
    <div class="container">
        <h3 class="center-align white-text shadow">Your Characters</h3>
    </div>

    <!-- Add character button -->
    <div class="row">
        <div class="col s12 center-align">
            <a href="{{ url_for('add_character') }}" class="btn-large shadow" aria-label="Add a new character">
                Add Character <i class="fas fa-plus-square right"></i>
            </a>
        </div>
    </div>

    <!-- Character display -->
    <div class="row">
        {% set sorted_characters = characters | sort(attribute='character_level', reverse=true) %}
        {% for character in sorted_characters %}
        <div class="col s12 m6 l4">
            <div class="card-panel shadow white-text z-depth-1">
                <div class="row valign-wrapper">
                    <div class="col s5">
                        <!-- Elif to display the correct image for the chosen race -->
                        {% if character.character_race == 'Dragonborn' %}
                        <img src="{{ url_for('static', filename='images/races/canva-dragonborn.webp') }}" alt="Dragonborn image" class="circle responsive-img">
                        {% elif character.character_race == 'Dwarf' %}
                        <img src="{{ url_for('static', filename='images/races/canva-dwarf.webp') }}" alt="Dwarf image" class="circle responsive-img">
                        {% elif character.character_race == 'Elf' %}
                        <img src="{{ url_for('static', filename='images/races/canva-elf.webp') }}" alt="Elf image" class="circle responsive-img">
                        {% elif character.character_race == 'Gnome' %}
                        <img src="{{ url_for('static', filename='images/races/canva-gnome.webp') }}" alt="Gnome image" class="circle responsive-img">
                        {% elif character.character_race == 'Half-Elf' %}
                        <img src="{{ url_for('static', filename='images/races/canva-half-elf.webp') }}" alt="Half-Elf image" class="circle responsive-img">
                        {% elif character.character_race == 'Halfling' %}
                        <img src="{{ url_for('static', filename='images/races/canva-halfling.webp') }}" alt="Halfling image" class="circle responsive-img">
                        {% elif character.character_race == 'Half-Orc' %}
                        <img src="{{ url_for('static', filename='images/races/canva-half-orc.webp') }}" alt="Half-Orc image" class="circle responsive-img">
                        {% elif character.character_race == 'Human' %}
                        <img src="{{ url_for('static', filename='images/races/canva-human.webp') }}" alt="Human image" class="circle responsive-img">
                        {% elif character.character_race == 'Tiefling' %}
                        <img src="{{ url_for('static', filename='images/races/canva-tiefling.webp') }}" alt="Tiefling image" class="circle responsive-img">
                        {% endif %}
                    </div>

                    <!-- Character information-->
                    <div class="col s10">
                        <p>{{ character.character_name }}</p>
                        <p>Level {{ character.character_level }}<br>{{character.character_race}}<br>{{character.character_class}}</p>
                        <div class="col s5">
                            <!-- View character -->
                            <a class="waves-effect waves-heavy btn-large shadow" href="{{ url_for('character_view', character_id=character.id) }}" aria-label="View chosen character">View</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}

rogues_den/templates/login.html
{% extends "base.html" %}
{% block content %}
    <div class="container">
        <h3 class="center-align white-text shadow">Login</h3>
    </div>

    <div class="row">
        <form class="col s12 l6 offset-l3" id="loginForm" method="POST" action="{{ url_for('auth.login') }}">
            <div class="row">
                <!-- Email Address Field -->
                <div class="input-field col s12 white-text shadow">
                    <input id="email" type="email" name="email" minlength="5" maxlength="55"
                        class="validate white-text" required>
                    <label class="white-text" for="email">Email Address</label>
                </div>
            </div>

            <div class="row">
                <!-- Password Field -->
                <div class="textbox tooltipped" data-position="top" data-tooltip="Please enter your password correctly">
                    <div class="input-field col s12 white-text shadow">
                        <input id="password" type="password" name="password" minlength="7"
                            maxlength="255" class="validate white-text" required>
                        <label class="white-text" for="password">Enter Password</label>
                    </div>
                </div>
            </div>

            <!-- Submit Button -->
            <div class="center-align">
                <button class="btn-large shadow" type="submit" aria-label="Login to account"><i class="material-icons">Login</i></button>
            </div>
            <br>
        </form>
    </div>
{% endblock %}

rogues_den/templates/profile.html
{% extends "base.html" %}
{% block content %}
    <div class="container">
        <h3 class="center-align white-text shadow">Your Profile</h3>
    </div>
    <div class="container">
        <div class="row">
            <!-- Profile image -->
            <div class="col s8 offset-s2 m6 offset-m3 l4 offset-l4">
                <img class="profile responsive-img" src="{{ url_for('static', filename='images/blank-profile-picture.webp') }}" alt="stock profile image">
            </div> 
        </div>

        <!-- User information -->
        <div class="row">
            <div class="col s8 offset-s2 center-align m6 offset-m3 l8 offset-l2">
                <p class="flow-text white-text shadow">Username: {{ users.username }}</p>
                <p class="flow-text white-text shadow">Name: {{ users.fname }} {{ users.lname }}</p>
            </div>
        </div>

        <!-- Logout button -->
        <div class="center-align">
            <a class="waves-effect waves-heavy btn-large shadow" href="{{ url_for('auth.logout') }}" aria-label="Logout of account">Logout</a>
        </div>
    </div>
{% endblock %}

rogues_den/templates/register.html
{% extends "base.html" %}
{% block content %}
    <div class="container">
        <h3 class="center-align white-text shadow">Register</h3>
    </div>

    <div class="row">
        <form class="col s12 l6 offset-l3" id="registrationForm" method="POST" action="{{ url_for('auth.register') }}">
            <div class="row">
                <!-- Username Field -->
                <div class="input-field col s12 white-text shadow">
                    <input id="username" type="text" name="username" minlength="1" maxlength="55"
                        class="validate white-text" required>
                    <label class="white-text" for="username">Username</label>
                </div>

                <!-- Email Address Field -->
                <div class="input-field col s12 white-text shadow">
                    <input id="email" type="email" name="email" minlength="5" maxlength="55"
                        class="validate white-text" required>
                    <label class="white-text" for="email">Email Address</label>
                </div>
            </div>

            <div class="row">
                <!-- First Name Field-->
                <div class="input-field col s6 white-text shadow">
                    <input id="fname" type="text" name="fname" minlength="1" maxlength="55"
                        class="validate white-text" required>
                    <label class="white-text" for="fname">First Name</label>
                </div>

                <!-- Surname Field -->
                <div class="input-field col s6 white-text shadow">
                    <input id="lname" type="text" name="lname" minlength="1" maxlength="55"
                        class="validate white-text" required>
                    <label class="white-text" for="lname">Surname</label>
                </div>
            </div>

            <div class="row">
                <!-- Password Field -->
                <div class="textbox tooltipped" data-position="top" data-tooltip="Your password must be at least 7 characters long">
                    <div class="input-field col s12 white-text shadow">
                        <input id="password1" type="password" name="password1" minlength="7"
                            maxlength="255" class="validate white-text" required>
                        <label class="white-text" for="password1">Enter Password</label>
                    </div>
                </div>
            </div>

            <div class="row">
                <!-- Confirm Password Field -->
                <div class="textbox tooltipped" data-position="top" data-tooltip="This password must match the above password">
                    <div class="input-field col s12 white-text shadow">
                        <input id="password2" type="password" name="password2" minlength="7"
                            maxlength="255" class="validate white-text" required>
                        <label class="white-text" for="password2">Confirm Password</label>
                    </div>
                </div>
            </div>

            <!-- Submit Button -->
            <div class="center-align">
                <button class="btn-large shadow" aria-label="Confirm registration"><i class="material-icons">Submit</i></button>
            </div>
        </form>
    </div>
{% endblock %}